server.port=8081
spring.application.name=spring-ai
#Gemini API Key
#spring.ai.google.genai.api-key=${GEMINI_API_KEY}
#spring.ai.google.genai.chat.options.model=gemini-2.5-flash
#spring.ai.google.genai.embedding.options.model=text-embedding-004


# OpenAI API Key
spring.ai.openai.api-key=${OPEN_AI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4.1-mini
spring.ai.openai.embedding.options.model=text-embedding-3-small

weather.api.key=${WEATHER_API_KEY}