spring.application.name=spring-ai
#Gemini API Key
#spring.ai.google.genai.api-key={GEMINI_API_KEY}
#spring.ai.google.genai.chat.options.model=gemini-3.5-flash


# Groq API Key
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama-3.1-8b-instant
